/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Badge, IconButton, SvgIcon } from '@mui/material';
import { IconStar } from 'lib';
import { styled } from '@mui/material/styles';

const Badge2 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-end`,
  alignItems: `flex-start`,
  padding: `20px 70px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const IconStar1 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
});

const IconButton1 = styled(IconButton)(({ theme }) => ({
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const BadgeWithComponent = styled(Badge)(({ theme }) => ({
  height: `32px`,
  width: `32px`,
  margin: `0px`,
  color: theme.palette['Primary']['Contrast'],
  fontStyle: theme.typography['Components']['Badge Label'].fontStyle,
  fontFamily: theme.typography['Components']['Badge Label'].fontFamily,
  fontWeight: theme.typography['Components']['Badge Label'].fontWeight,
  fontSize: theme.typography['Components']['Badge Label'].fontSize,
  letterSpacing: theme.typography['Components']['Badge Label'].letterSpacing,
  lineHeight: theme.typography['Components']['Badge Label'].lineHeight,
  textDecoration: theme.typography['Components']['Badge Label'].textDecoration,
  textTransform: theme.typography['Components']['Badge Label'].textTransform,
}));

const IconStar2 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
});

const IconButton2 = styled(IconButton)(({ theme }) => ({
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const BadgeWithComponent1 = styled(Badge)(({ theme }) => ({
  height: `32px`,
  width: `32px`,
  margin: `40px 0px 0px 0px`,
  color: theme.palette['Secondary']['Contrast'],
  fontStyle: theme.typography['Components']['Badge Label'].fontStyle,
  fontFamily: theme.typography['Components']['Badge Label'].fontFamily,
  fontWeight: theme.typography['Components']['Badge Label'].fontWeight,
  fontSize: theme.typography['Components']['Badge Label'].fontSize,
  letterSpacing: theme.typography['Components']['Badge Label'].letterSpacing,
  lineHeight: theme.typography['Components']['Badge Label'].lineHeight,
  textDecoration: theme.typography['Components']['Badge Label'].textDecoration,
  textTransform: theme.typography['Components']['Badge Label'].textTransform,
}));

const IconStar3 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
});

const IconButton3 = styled(IconButton)(({ theme }) => ({
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const BadgeWithComponent2 = styled(Badge)(({ theme }) => ({
  height: `32px`,
  width: `32px`,
  margin: `40px 0px 0px 0px`,
  color: theme.palette['Error']['Contrast'],
  fontStyle: theme.typography['Components']['Badge Label'].fontStyle,
  fontFamily: theme.typography['Components']['Badge Label'].fontFamily,
  fontWeight: theme.typography['Components']['Badge Label'].fontWeight,
  fontSize: theme.typography['Components']['Badge Label'].fontSize,
  letterSpacing: theme.typography['Components']['Badge Label'].letterSpacing,
  lineHeight: theme.typography['Components']['Badge Label'].lineHeight,
  textDecoration: theme.typography['Components']['Badge Label'].textDecoration,
  textTransform: theme.typography['Components']['Badge Label'].textTransform,
}));

const IconStar4 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
});

const IconButton4 = styled(IconButton)(({ theme }) => ({
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const BadgeWithComponent3 = styled(Badge)(({ theme }) => ({
  height: `32px`,
  width: `32px`,
  margin: `40px 0px 0px 0px`,
}));

const IconStar5 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
});

const IconButton5 = styled(IconButton)(({ theme }) => ({
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const BadgeWithComponent4 = styled(Badge)(({ theme }) => ({
  height: `32px`,
  width: `32px`,
  margin: `40px 0px 0px 0px`,
}));

const IconStar6 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
});

const IconButton6 = styled(IconButton)(({ theme }) => ({
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const BadgeWithComponent5 = styled(Badge)(({ theme }) => ({
  height: `32px`,
  width: `32px`,
  margin: `40px 0px 0px 0px`,
}));

const IconStar7 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
});

const IconButton7 = styled(IconButton)(({ theme }) => ({
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const BadgeWithComponent6 = styled(Badge)(({ theme }) => ({
  height: `32px`,
  width: `32px`,
  margin: `40px 0px 0px 0px`,
}));

function Badge1(props) {
  return (
    <Badge2 className={props.className}>
      <BadgeWithComponent
        color={'primary'}
        variant={'standard'}
        badgeContent={12}
      >
        <IconButton1 size={'medium'} color={'default'} disabled={false}>
          <IconStar1 fontSize={'inherit'} component={IconStar} />
        </IconButton1>
      </BadgeWithComponent>
      <BadgeWithComponent1
        color={'secondary'}
        variant={'standard'}
        badgeContent={1}
      >
        <IconButton2 size={'medium'} color={'default'} disabled={false}>
          <IconStar2 fontSize={'inherit'} component={IconStar} />
        </IconButton2>
      </BadgeWithComponent1>
      <BadgeWithComponent2
        color={'error'}
        variant={'standard'}
        badgeContent={1}
      >
        <IconButton3 size={'medium'} color={'default'} disabled={false}>
          <IconStar3 fontSize={'inherit'} component={IconStar} />
        </IconButton3>
      </BadgeWithComponent2>
      <BadgeWithComponent3 color={'error'} variant={'dot'}>
        <IconButton4 size={'medium'} color={'default'} disabled={false}>
          <IconStar4 fontSize={'inherit'} component={IconStar} />
        </IconButton4>
      </BadgeWithComponent3>
      <BadgeWithComponent4 color={'warning'} variant={'dot'}>
        <IconButton5 size={'medium'} color={'default'} disabled={false}>
          <IconStar5 fontSize={'inherit'} component={IconStar} />
        </IconButton5>
      </BadgeWithComponent4>
      <BadgeWithComponent5 color={'info'} variant={'dot'}>
        <IconButton6 size={'medium'} color={'default'} disabled={false}>
          <IconStar6 fontSize={'inherit'} component={IconStar} />
        </IconButton6>
      </BadgeWithComponent5>
      <BadgeWithComponent6 color={'success'} variant={'dot'}>
        <IconButton7 size={'medium'} color={'default'} disabled={false}>
          <IconStar7 fontSize={'inherit'} component={IconStar} />
        </IconButton7>
      </BadgeWithComponent6>
    </Badge2>
  );
}

export default Badge1;
