/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { SvgIcon } from '@mui/material';
import { IconStar } from 'lib';
import { styled } from '@mui/material/styles';

const Icon2 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `314px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const IconStar1 = styled(SvgIcon)({
  alignSelf: `stretch`,
  flex: `1`,
  width: `20px`,
  height: `20px`,
  position: `absolute`,
  left: `28px`,
  top: `85px`,
});

const IconStar2 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
  position: `absolute`,
  left: `26px`,
  top: `56px`,
});

const IconStar3 = styled(SvgIcon)({
  alignSelf: `stretch`,
  flex: `1`,
  width: `36px`,
  height: `36px`,
  position: `absolute`,
  left: `20px`,
  top: `19px`,
});

function Icon1(props) {
  return (
    <Icon2 className={props.className}>
      <IconStar1 fontSize={'inherit'} component={IconStar} />
      <IconStar2 fontSize={'inherit'} component={IconStar} />
      <IconStar3 fontSize={'inherit'} component={IconStar} />
    </Icon2>
  );
}

export default Icon1;
