/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Pagination } from '@mui/material';
import { styled } from '@mui/material/styles';

const Pagination2 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `30px 20px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const Pagination3 = styled(Pagination)(({ theme }) => ({
  margin: `0px`,
}));

const Pagination4 = styled(Pagination)(({ theme }) => ({
  margin: `30px 0px 0px 0px`,
}));

const Pagination5 = styled(Pagination)(({ theme }) => ({
  margin: `30px 0px 0px 0px`,
}));

const Pagination6 = styled(Pagination)(({ theme }) => ({
  margin: `30px 0px 0px 0px`,
}));

const Pagination7 = styled(Pagination)(({ theme }) => ({
  margin: `30px 0px 0px 0px`,
}));

const Pagination8 = styled(Pagination)(({ theme }) => ({
  margin: `30px 0px 0px 0px`,
}));

const Pagination9 = styled(Pagination)(({ theme }) => ({
  margin: `30px 0px 0px 0px`,
}));

const Pagination10 = styled(Pagination)(({ theme }) => ({
  margin: `30px 0px 0px 0px`,
}));

const Pagination11 = styled(Pagination)(({ theme }) => ({
  margin: `30px 0px 0px 0px`,
}));

const Pagination12 = styled(Pagination)(({ theme }) => ({
  margin: `30px 0px 0px 0px`,
}));

function Pagination1(props) {
  return (
    <Pagination2 className={props.className}>
      <Pagination3
        count={10}
        size={'large'}
        color={'standard'}
        shape={'circular'}
        disabled={true}
      ></Pagination3>
      <Pagination4
        count={10}
        size={'large'}
        color={'standard'}
        shape={'rounded'}
        disabled={false}
      ></Pagination4>
      <Pagination5
        count={10}
        size={'large'}
        color={'primary'}
        shape={'circular'}
        disabled={false}
      ></Pagination5>
      <Pagination6
        count={10}
        size={'large'}
        color={'secondary'}
        shape={'circular'}
        disabled={false}
      ></Pagination6>
      <Pagination7
        count={10}
        size={'medium'}
        color={'standard'}
        shape={'circular'}
        disabled={false}
      ></Pagination7>
      <Pagination8
        count={10}
        size={'medium'}
        color={'standard'}
        shape={'rounded'}
        disabled={false}
      ></Pagination8>
      <Pagination9
        count={10}
        size={'medium'}
        color={'primary'}
        shape={'circular'}
        disabled={false}
      ></Pagination9>
      <Pagination10
        count={10}
        size={'medium'}
        color={'standard'}
        shape={'rounded'}
        disabled={true}
      ></Pagination10>
      <Pagination11
        count={10}
        size={'small'}
        color={'standard'}
        shape={'circular'}
        disabled={false}
      ></Pagination11>
      <Pagination12
        count={10}
        size={'small'}
        color={'standard'}
        shape={'rounded'}
        disabled={false}
      ></Pagination12>
    </Pagination2>
  );
}

export default Pagination1;
