/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Skeleton } from '@mui/material';
import { styled } from '@mui/material/styles';

const Skeleton2 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `30px 20px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const Skeleton3 = styled(Skeleton)(({ theme }) => ({
  height: `40px`,
  width: `40px`,
  margin: `0px`,
}));

const Skeleton4 = styled(Skeleton)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `120px`,
  margin: `20px 0px 0px 0px`,
  animation: 'wave',
}));

const Skeleton5 = styled(Skeleton)(({ theme }) => ({
  height: `14px`,
  width: `120px`,
  margin: `20px 0px 0px 0px`,
}));

function Skeleton1(props) {
  return (
    <Skeleton2 className={props.className}>
      <Skeleton3 variant={'circular'} />
      <Skeleton4 variant={'rectangular'} animation={'wave'} />
      <Skeleton5 variant={'text'} />
    </Skeleton2>
  );
}

export default Skeleton1;
