/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { LinearProgress } from '@mui/material';
import { styled } from '@mui/material/styles';

const Progress1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `50px 20px`,
  boxSizing: `border-box`,
  height: 'auto',
});

const ProgressLinear = styled(LinearProgress)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `4px`,
  margin: `0px`,
}));

const ProgressLinear1 = styled(LinearProgress)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `4px`,
  margin: `22px 0px 0px 0px`,
}));

const ProgressLinear2 = styled(LinearProgress)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `4px`,
  margin: `22px 0px 0px 0px`,
}));

const ProgressLinear3 = styled(LinearProgress)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `4px`,
  margin: `22px 0px 0px 0px`,
}));

const ProgressLinear4 = styled(LinearProgress)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `4px`,
  margin: `22px 0px 0px 0px`,
}));

const ProgressLinear5 = styled(LinearProgress)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `4px`,
  margin: `22px 0px 0px 0px`,
}));

function Progress(props) {
  return (
    <Progress1 className={props.className}>
      <ProgressLinear
        variant={'determinate'}
        color={'primary'}
        value={'80%'}
      ></ProgressLinear>
      <ProgressLinear1
        variant={'indeterminate'}
        color={'primary'}
        valueBuffer={true}
      ></ProgressLinear1>
      <ProgressLinear2
        variant={'determinate'}
        color={'secondary'}
      ></ProgressLinear2>
      <ProgressLinear3
        variant={'determinate'}
        color={'secondary'}
      ></ProgressLinear3>
      <ProgressLinear4
        variant={'determinate'}
        color={'inherit'}
      ></ProgressLinear4>
      <ProgressLinear5
        variant={'indeterminate'}
        color={'inherit'}
      ></ProgressLinear5>
    </Progress1>
  );
}

export default Progress;
