/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Rating } from '@mui/material';
import { styled } from '@mui/material/styles';

const Rating2 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `20px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const Rating3 = styled(Rating)(({ theme }) => ({
  margin: `0px`,
}));

const Rating4 = styled(Rating)(({ theme }) => ({
  margin: `25px 0px 0px 0px`,
}));

const Rating5 = styled(Rating)(({ theme }) => ({
  margin: `25px 0px 0px 0px`,
}));

const Rating6 = styled(Rating)(({ theme }) => ({
  margin: `25px 0px 0px 0px`,
}));

const Rating7 = styled(Rating)(({ theme }) => ({
  margin: `25px 0px 0px 0px`,
}));

const Rating8 = styled(Rating)(({ theme }) => ({
  margin: `25px 0px 0px 0px`,
}));

function Rating1(props) {
  return (
    <Rating2 className={props.className}>
      <Rating3 size={'large'} disabled={false} max={3} precision={0.5} />
      <Rating4 size={'medium'} disabled={false} />
      <Rating5 size={'small'} disabled={false} />
      <Rating6 size={'large'} disabled={true} />
      <Rating7 size={'medium'} disabled={true} />
      <Rating8 size={'small'} disabled={true} />
    </Rating2>
  );
}

export default Rating1;
