/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
const useButton1 = () => {
  const [disabled, setDisabled] = React.useState(false);

  const disableButtons = () => {
    setDisabled(true);
  };
  const enableButtons = () => {
    setDisabled(false);
  };

  const data = { disabled };

  const fns = { disableButtons, enableButtons };

  return { data, fns };
};

export default useButton1;
