/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { BottomNavigation, SvgIcon } from '@mui/material';
import BottomNavigationAction from '@mui/material/BottomNavigationAction';
import { IconHome } from 'lib';
import { styled } from '@mui/material/styles';

const BottomNav1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `30px 20px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const IconHome1 = styled(SvgIcon)({
  height: `24px`,
  width: `24px`,
});

const BottomNavigationElem = styled(BottomNavigationAction)(({ theme }) => ({
  alignSelf: `stretch`,
  flex: `1`,
  margin: `0px`,
  color: theme.palette['Text']['Secondary'],
  fontStyle:
    theme.typography['Components']['Bottom Navigation Active Label'].fontStyle,
  fontFamily:
    theme.typography['Components']['Bottom Navigation Active Label'].fontFamily,
  fontWeight:
    theme.typography['Components']['Bottom Navigation Active Label'].fontWeight,
  fontSize:
    theme.typography['Components']['Bottom Navigation Active Label'].fontSize,
  letterSpacing:
    theme.typography['Components']['Bottom Navigation Active Label']
      .letterSpacing,
  lineHeight:
    theme.typography['Components']['Bottom Navigation Active Label'].lineHeight,
  textDecoration:
    theme.typography['Components']['Bottom Navigation Active Label']
      .textDecoration,
  textTransform:
    theme.typography['Components']['Bottom Navigation Active Label']
      .textTransform,
}));

const IconHome2 = styled(SvgIcon)({
  height: `24px`,
  width: `24px`,
});

const BottomNavigationElem1 = styled(BottomNavigationAction)(({ theme }) => ({
  alignSelf: `stretch`,
  flex: `1`,
  margin: `0px`,
  color: theme.palette['Text']['Secondary'],
  fontStyle:
    theme.typography['Components']['Bottom Navigation Active Label'].fontStyle,
  fontFamily:
    theme.typography['Components']['Bottom Navigation Active Label'].fontFamily,
  fontWeight:
    theme.typography['Components']['Bottom Navigation Active Label'].fontWeight,
  fontSize:
    theme.typography['Components']['Bottom Navigation Active Label'].fontSize,
  letterSpacing:
    theme.typography['Components']['Bottom Navigation Active Label']
      .letterSpacing,
  lineHeight:
    theme.typography['Components']['Bottom Navigation Active Label'].lineHeight,
  textDecoration:
    theme.typography['Components']['Bottom Navigation Active Label']
      .textDecoration,
  textTransform:
    theme.typography['Components']['Bottom Navigation Active Label']
      .textTransform,
}));

const IconHome3 = styled(SvgIcon)({
  height: `24px`,
  width: `24px`,
});

const BottomNavigationElem2 = styled(BottomNavigationAction)(({ theme }) => ({
  alignSelf: `stretch`,
  flex: `1`,
  margin: `0px`,
  color: theme.palette['Text']['Disabled'],
  fontStyle:
    theme.typography['Components']['Bottom Navigation Active Label'].fontStyle,
  fontFamily:
    theme.typography['Components']['Bottom Navigation Active Label'].fontFamily,
  fontWeight:
    theme.typography['Components']['Bottom Navigation Active Label'].fontWeight,
  fontSize:
    theme.typography['Components']['Bottom Navigation Active Label'].fontSize,
  letterSpacing:
    theme.typography['Components']['Bottom Navigation Active Label']
      .letterSpacing,
  lineHeight:
    theme.typography['Components']['Bottom Navigation Active Label'].lineHeight,
  textDecoration:
    theme.typography['Components']['Bottom Navigation Active Label']
      .textDecoration,
  textTransform:
    theme.typography['Components']['Bottom Navigation Active Label']
      .textTransform,
}));

const BottomNavigation1 = styled(BottomNavigation)(({ theme }) => ({
  height: `56px`,
  width: `500px`,
  margin: `0px`,
}));

const IconHome4 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
});

const BottomNavigationElem3 = styled(BottomNavigationAction)(({ theme }) => ({
  alignSelf: `stretch`,
  flex: `1`,
  margin: `0px`,
}));

const IconHome5 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
});

const BottomNavigationElem4 = styled(BottomNavigationAction)(({ theme }) => ({
  alignSelf: `stretch`,
  flex: `1`,
  margin: `0px`,
}));

const IconHome6 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
});

const BottomNavigationElem5 = styled(BottomNavigationAction)(({ theme }) => ({
  alignSelf: `stretch`,
  flex: `1`,
  margin: `0px`,
}));

const IconHome7 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
});

const BottomNavigationElem6 = styled(BottomNavigationAction)(({ theme }) => ({
  alignSelf: `stretch`,
  flex: `1`,
  margin: `0px`,
}));

const BottomNavigation2 = styled(BottomNavigation)(({ theme }) => ({
  height: `56px`,
  width: `500px`,
  margin: `24px 0px 0px 0px`,
}));

function BottomNav(props) {
  return (
    <BottomNav1 className={props.className}>
      <BottomNavigation1 showLabels={true}>
        <BottomNavigationElem
          disabled={false}
          label={'Label'}
          icon={<IconHome1 fontSize={'inherit'} component={IconHome} />}
        ></BottomNavigationElem>
        <BottomNavigationElem1
          disabled={false}
          label={'Label'}
          icon={<IconHome2 fontSize={'inherit'} component={IconHome} />}
        ></BottomNavigationElem1>
        <BottomNavigationElem2
          disabled={true}
          label={'Label'}
          icon={<IconHome3 fontSize={'inherit'} component={IconHome} />}
        ></BottomNavigationElem2>
      </BottomNavigation1>
      <BottomNavigation2 showLabels={false}>
        <BottomNavigationElem3
          disabled={false}
          icon={<IconHome4 fontSize={'inherit'} component={IconHome} />}
        ></BottomNavigationElem3>
        <BottomNavigationElem4
          disabled={false}
          icon={<IconHome5 fontSize={'inherit'} component={IconHome} />}
        ></BottomNavigationElem4>
        <BottomNavigationElem5
          disabled={true}
          icon={<IconHome6 fontSize={'inherit'} component={IconHome} />}
        ></BottomNavigationElem5>
        <BottomNavigationElem6
          disabled={false}
          icon={<IconHome7 fontSize={'inherit'} component={IconHome} />}
        ></BottomNavigationElem6>
      </BottomNavigation2>
    </BottomNav1>
  );
}

export default BottomNav;
