/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Avatar, SvgIcon } from '@mui/material';
import { IconStar } from 'lib';
import { Helmet } from 'react-helmet-async';
import { styled } from '@mui/material/styles';

const Avatar2 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `20px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
  width: 'fit-content',
});

const Frame2 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Avatar3 = styled(Avatar)(({ theme }) => ({
  height: `40px`,
  width: `40px`,
  margin: `0px`,
}));

const Avatar4 = styled(Avatar)(({ theme }) => ({
  height: `40px`,
  width: `40px`,
  margin: `20px 0px 0px 0px`,
  color: theme.palette['Text']['Secondary'],
  fontStyle: theme.typography['Components']['Avatar Initials'].fontStyle,
  fontFamily: theme.typography['Components']['Avatar Initials'].fontFamily,
  fontWeight: theme.typography['Components']['Avatar Initials'].fontWeight,
  fontSize: theme.typography['Components']['Avatar Initials'].fontSize,
  letterSpacing:
    theme.typography['Components']['Avatar Initials'].letterSpacing,
  lineHeight: theme.typography['Components']['Avatar Initials'].lineHeight,
  textDecoration:
    theme.typography['Components']['Avatar Initials'].textDecoration,
  textTransform:
    theme.typography['Components']['Avatar Initials'].textTransform,
}));

const IconStar1 = styled(SvgIcon)({
  flex: `1`,
});

const Avatar5 = styled(Avatar)(({ theme }) => ({
  height: `40px`,
  width: `40px`,
  margin: `20px 0px 0px 0px`,
}));

const IconStar2 = styled(SvgIcon)({
  flex: `1`,
});

const Avatar6 = styled(Avatar)(({ theme }) => ({
  height: `24px`,
  width: `24px`,
  margin: `20px 0px 0px 0px`,
}));

const Avatar7 = styled(Avatar)(({ theme }) => ({
  height: `24px`,
  width: `24px`,
  margin: `20px 0px 0px 0px`,
}));

const Avatar8 = styled(Avatar)(({ theme }) => ({
  height: `24px`,
  width: `24px`,
  margin: `20px 0px 0px 0px`,
  color: theme.palette['Text']['Secondary'],
  fontStyle: theme.typography['Typography']['Caption'].fontStyle,
  fontFamily: theme.typography['Typography']['Caption'].fontFamily,
  fontWeight: theme.typography['Typography']['Caption'].fontWeight,
  fontSize: theme.typography['Typography']['Caption'].fontSize,
  letterSpacing: theme.typography['Typography']['Caption'].letterSpacing,
  lineHeight: theme.typography['Typography']['Caption'].lineHeight,
  textDecoration: theme.typography['Typography']['Caption'].textDecoration,
  textTransform: theme.typography['Typography']['Caption'].textTransform,
}));

const IconStar3 = styled(SvgIcon)({
  flex: `1`,
});

const Avatar9 = styled(Avatar)(({ theme }) => ({
  height: `24px`,
  width: `24px`,
  margin: `20px 0px 0px 0px`,
}));

const Avatar10 = styled(Avatar)(({ theme }) => ({
  height: `40px`,
  width: `40px`,
  margin: `20px 0px 0px 0px`,
}));

const Avatar11 = styled(Avatar)(({ theme }) => ({
  height: `40px`,
  width: `40px`,
  margin: `20px 0px 0px 0px`,
  color: theme.palette['Text']['Secondary'],
  fontStyle: theme.typography['Components']['Avatar Initials'].fontStyle,
  fontFamily: theme.typography['Components']['Avatar Initials'].fontFamily,
  fontWeight: theme.typography['Components']['Avatar Initials'].fontWeight,
  fontSize: theme.typography['Components']['Avatar Initials'].fontSize,
  letterSpacing:
    theme.typography['Components']['Avatar Initials'].letterSpacing,
  lineHeight: theme.typography['Components']['Avatar Initials'].lineHeight,
  textDecoration:
    theme.typography['Components']['Avatar Initials'].textDecoration,
  textTransform:
    theme.typography['Components']['Avatar Initials'].textTransform,
}));

const IconStar4 = styled(SvgIcon)({
  flex: `1`,
});

const Avatar12 = styled(Avatar)(({ theme }) => ({
  height: `40px`,
  width: `40px`,
  margin: `20px 0px 0px 0px`,
}));

const Avatar13 = styled(Avatar)(({ theme }) => ({
  height: `24px`,
  width: `24px`,
  margin: `20px 0px 0px 0px`,
}));

function Avatar1(props) {
  return (
    <Avatar2 className={props.className}>
      <Helmet>
        <title>Avatar for you</title>
        <meta
          name="description"
          content="this is a the avatar page
"
        />
      </Helmet>
      <Frame2>
        <Avatar3
          src="assets/images/Avatar___Avatar___.png"
          sx={{ width: 40, height: 40 }}
          variant={'circular'}
        ></Avatar3>
        <Avatar4 sx={{ width: 40, height: 40 }} variant={'circular'}>
          {'aj'}
        </Avatar4>
        {false && (
          <Avatar5 sx={{ width: 40, height: 40 }} variant={'circular'}>
            <IconStar1 fontSize={'inherit'} component={IconStar} />
          </Avatar5>
        )}
        <Avatar6 sx={{ width: 24, height: 24 }} variant={'circular'}>
          <IconStar2 fontSize={'inherit'} component={IconStar} />
        </Avatar6>
        <Avatar7
          src="assets/images/Avatar___Avatar____1.png"
          sx={{ width: 24, height: 24 }}
          variant={'square'}
        ></Avatar7>
        <Avatar8 sx={{ width: 24, height: 24 }} variant={'square'}>
          {'QR'}
        </Avatar8>
        <Avatar9 sx={{ width: 24, height: 24 }} variant={'square'}>
          <IconStar3 fontSize={'inherit'} component={IconStar} />
        </Avatar9>
        <Avatar10
          src="assets/images/Avatar___Avatar____2.png"
          sx={{ width: 40, height: 40 }}
          variant={'rounded'}
        ></Avatar10>
        <Avatar11 sx={{ width: 40, height: 40 }} variant={'rounded'}>
          {'QR'}
        </Avatar11>
        <Avatar12 sx={{ width: 40, height: 40 }} variant={'rounded'}>
          <IconStar4 fontSize={'inherit'} component={IconStar} />
        </Avatar12>
        <Avatar13
          src="assets/images/Avatar___Avatar____3.png"
          sx={{ width: 24, height: 24 }}
          variant={'rounded'}
        ></Avatar13>
      </Frame2>
    </Avatar2>
  );
}

export default Avatar1;
