/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Fab, SvgIcon } from '@mui/material';
import { IconAdd } from 'lib';
import { styled } from '@mui/material/styles';

const Fab2 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `30px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const IconAdd1 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
  margin: `0px`,
});

const FloatingActionButton = styled(Fab)(({ theme }) => ({
  margin: `0px`,
  fontStyle: theme.typography['Components']['Button Font - Large'].fontStyle,
  fontFamily: theme.typography['Components']['Button Font - Large'].fontFamily,
  fontWeight: theme.typography['Components']['Button Font - Large'].fontWeight,
  fontSize: theme.typography['Components']['Button Font - Large'].fontSize,
  letterSpacing:
    theme.typography['Components']['Button Font - Large'].letterSpacing,
  lineHeight: theme.typography['Components']['Button Font - Large'].lineHeight,
  textDecoration:
    theme.typography['Components']['Button Font - Large'].textDecoration,
  textTransform:
    theme.typography['Components']['Button Font - Large'].textTransform,
  gap: `5px`,
}));

const IconAdd2 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
  margin: `0px`,
});

const FloatingActionButton1 = styled(Fab)(({ theme }) => ({
  margin: `32px 0px 0px 0px`,
  color: theme.palette['Primary']['Contrast'],
  fontStyle: theme.typography['Components']['Button Font - Large'].fontStyle,
  fontFamily: theme.typography['Components']['Button Font - Large'].fontFamily,
  fontWeight: theme.typography['Components']['Button Font - Large'].fontWeight,
  fontSize: theme.typography['Components']['Button Font - Large'].fontSize,
  letterSpacing:
    theme.typography['Components']['Button Font - Large'].letterSpacing,
  lineHeight: theme.typography['Components']['Button Font - Large'].lineHeight,
  textDecoration:
    theme.typography['Components']['Button Font - Large'].textDecoration,
  textTransform:
    theme.typography['Components']['Button Font - Large'].textTransform,
  gap: `5px`,
}));

const IconAdd3 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
  margin: `0px`,
});

const FloatingActionButton2 = styled(Fab)(({ theme }) => ({
  margin: `32px 0px 0px 0px`,
  color: theme.palette['Secondary']['Contrast'],
  fontStyle: theme.typography['Components']['Button Font - Large'].fontStyle,
  fontFamily: theme.typography['Components']['Button Font - Large'].fontFamily,
  fontWeight: theme.typography['Components']['Button Font - Large'].fontWeight,
  fontSize: theme.typography['Components']['Button Font - Large'].fontSize,
  letterSpacing:
    theme.typography['Components']['Button Font - Large'].letterSpacing,
  lineHeight: theme.typography['Components']['Button Font - Large'].lineHeight,
  textDecoration:
    theme.typography['Components']['Button Font - Large'].textDecoration,
  textTransform:
    theme.typography['Components']['Button Font - Large'].textTransform,
  gap: `5px`,
}));

const IconAdd4 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
  margin: `0px`,
});

const FloatingActionButton3 = styled(Fab)(({ theme }) => ({
  margin: `32px 0px 0px 0px`,
  color: theme.palette['Text']['Primary'],
  fontStyle: theme.typography['Components']['Button Font - Medium'].fontStyle,
  fontFamily: theme.typography['Components']['Button Font - Medium'].fontFamily,
  fontWeight: theme.typography['Components']['Button Font - Medium'].fontWeight,
  fontSize: theme.typography['Components']['Button Font - Medium'].fontSize,
  letterSpacing:
    theme.typography['Components']['Button Font - Medium'].letterSpacing,
  lineHeight: theme.typography['Components']['Button Font - Medium'].lineHeight,
  textDecoration:
    theme.typography['Components']['Button Font - Medium'].textDecoration,
  textTransform:
    theme.typography['Components']['Button Font - Medium'].textTransform,
  gap: `5px`,
}));

const IconAdd5 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
  margin: `0px`,
});

const FloatingActionButton4 = styled(Fab)(({ theme }) => ({
  margin: `32px 0px 0px 0px`,
  color: theme.palette['Primary']['Contrast'],
  fontStyle: theme.typography['Components']['Button Font - Medium'].fontStyle,
  fontFamily: theme.typography['Components']['Button Font - Medium'].fontFamily,
  fontWeight: theme.typography['Components']['Button Font - Medium'].fontWeight,
  fontSize: theme.typography['Components']['Button Font - Medium'].fontSize,
  letterSpacing:
    theme.typography['Components']['Button Font - Medium'].letterSpacing,
  lineHeight: theme.typography['Components']['Button Font - Medium'].lineHeight,
  textDecoration:
    theme.typography['Components']['Button Font - Medium'].textDecoration,
  textTransform:
    theme.typography['Components']['Button Font - Medium'].textTransform,
  gap: `5px`,
}));

const IconAdd6 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
  margin: `0px`,
});

const FloatingActionButton5 = styled(Fab)(({ theme }) => ({
  margin: `32px 0px 0px 0px`,
  gap: `5px`,
}));

const IconAdd7 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
  margin: `0px`,
});

const FloatingActionButton6 = styled(Fab)(({ theme }) => ({
  margin: `32px 0px 0px 0px`,
  gap: `5px`,
}));

const IconAdd8 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
  margin: `0px`,
});

const FloatingActionButton7 = styled(Fab)(({ theme }) => ({
  margin: `32px 0px 0px 0px`,
  gap: `5px`,
}));

const IconAdd9 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
  margin: `0px`,
});

const FloatingActionButton8 = styled(Fab)(({ theme }) => ({
  margin: `32px 0px 0px 0px`,
  color: theme.palette['Action']['Disabled'],
  fontStyle: theme.typography['Components']['Button Font - Medium'].fontStyle,
  fontFamily: theme.typography['Components']['Button Font - Medium'].fontFamily,
  fontWeight: theme.typography['Components']['Button Font - Medium'].fontWeight,
  fontSize: theme.typography['Components']['Button Font - Medium'].fontSize,
  letterSpacing:
    theme.typography['Components']['Button Font - Medium'].letterSpacing,
  lineHeight: theme.typography['Components']['Button Font - Medium'].lineHeight,
  textDecoration:
    theme.typography['Components']['Button Font - Medium'].textDecoration,
  textTransform:
    theme.typography['Components']['Button Font - Medium'].textTransform,
  gap: `5px`,
}));

const IconAdd10 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
  margin: `0px`,
});

const FloatingActionButton9 = styled(Fab)(({ theme }) => ({
  margin: `32px 0px 0px 0px`,
  color: theme.palette['Primary']['Contrast'],
  fontStyle: theme.typography['Components']['Button Font - Medium'].fontStyle,
  fontFamily: theme.typography['Components']['Button Font - Medium'].fontFamily,
  fontWeight: theme.typography['Components']['Button Font - Medium'].fontWeight,
  fontSize: theme.typography['Components']['Button Font - Medium'].fontSize,
  letterSpacing:
    theme.typography['Components']['Button Font - Medium'].letterSpacing,
  lineHeight: theme.typography['Components']['Button Font - Medium'].lineHeight,
  textDecoration:
    theme.typography['Components']['Button Font - Medium'].textDecoration,
  textTransform:
    theme.typography['Components']['Button Font - Medium'].textTransform,
  gap: `5px`,
}));

const IconAdd11 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
  margin: `0px`,
});

const FloatingActionButton10 = styled(Fab)(({ theme }) => ({
  margin: `32px 0px 0px 0px`,
  gap: `5px`,
}));

const IconAdd12 = styled(SvgIcon)({
  width: `24px`,
  height: `24px`,
  margin: `0px`,
});

const FloatingActionButton11 = styled(Fab)(({ theme }) => ({
  margin: `32px 0px 0px 0px`,
  gap: `5px`,
}));

function Fab1(props) {
  return (
    <Fab2 className={props.className}>
      <FloatingActionButton
        size={'large'}
        color={'primary'}
        disabled={false}
        variant={'extended'}
      >
        {'Fab'}
        <IconAdd1 fontSize={'inherit'} component={IconAdd} />
      </FloatingActionButton>
      <FloatingActionButton1
        size={'large'}
        color={'primary'}
        disabled={false}
        variant={'extended'}
      >
        {'Fab'}
        <IconAdd2 fontSize={'inherit'} component={IconAdd} />
      </FloatingActionButton1>
      <FloatingActionButton2
        size={'large'}
        color={'secondary'}
        disabled={false}
        variant={'extended'}
      >
        {'Fab'}
        <IconAdd3 fontSize={'inherit'} component={IconAdd} />
      </FloatingActionButton2>
      <FloatingActionButton3
        size={'medium'}
        color={'default'}
        disabled={false}
        variant={'extended'}
      >
        {'Fab'}
        <IconAdd4 fontSize={'inherit'} component={IconAdd} />
      </FloatingActionButton3>
      <FloatingActionButton4
        size={'medium'}
        color={'primary'}
        disabled={false}
        variant={'extended'}
      >
        {'Fab'}
        <IconAdd5 fontSize={'inherit'} component={IconAdd} />
      </FloatingActionButton4>
      <FloatingActionButton5
        size={'medium'}
        color={'default'}
        disabled={false}
        variant={'circular'}
      >
        <IconAdd6 fontSize={'inherit'} component={IconAdd} />
      </FloatingActionButton5>
      <FloatingActionButton6
        size={'medium'}
        color={'primary'}
        disabled={false}
        variant={'circular'}
      >
        <IconAdd7 fontSize={'inherit'} component={IconAdd} />
      </FloatingActionButton6>
      <FloatingActionButton7
        size={'medium'}
        color={'secondary'}
        disabled={false}
        variant={'circular'}
      >
        <IconAdd8 fontSize={'inherit'} component={IconAdd} />
      </FloatingActionButton7>
      <FloatingActionButton8
        size={'medium'}
        color={'secondary'}
        disabled={true}
        variant={'extended'}
      >
        {'Fab'}
        <IconAdd9 fontSize={'inherit'} component={IconAdd} />
      </FloatingActionButton8>
      <FloatingActionButton9
        size={'small'}
        color={'primary'}
        disabled={false}
        variant={'extended'}
      >
        {'Fab'}
        <IconAdd10 fontSize={'inherit'} component={IconAdd} />
      </FloatingActionButton9>
      <FloatingActionButton10
        size={'small'}
        color={'default'}
        disabled={false}
        variant={'circular'}
      >
        <IconAdd11 fontSize={'inherit'} component={IconAdd} />
      </FloatingActionButton10>
      <FloatingActionButton11
        size={'small'}
        color={'primary'}
        disabled={false}
        variant={'circular'}
      >
        <IconAdd12 fontSize={'inherit'} component={IconAdd} />
      </FloatingActionButton11>
    </Fab2>
  );
}

export default Fab1;
